[package]
name = "Ping_bybit_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3"
tokio= { version = "1.35.0", features = ["full"] }
tokio-tungstenite = {version = "0.21.0", features = ["native-tls"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.114"
url = "2.5.0"
hyper = "0.14"
object = "0.32.2"
reqwest = "0.11.24"
hyper-tls = "0.5.0"

[profile.release]
opt-level = 3

